CREATE TABLE "chat_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_query" text,
  "llm_response" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "search_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "chat_id" integer,
  "generated_query_1" text,
  "search_link_1" text,
  "generated_query_2" text,
  "search_link_2" text,
  "generated_query_3" text,
  "search_link_3" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "llm_processing_steps" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "chat_id" integer,
  "expanded_prompt" text
);

CREATE TABLE "links" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "search_link" text,
  "title" text,
  "content" text,
  "similarity" float
);

CREATE TABLE "links_searches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "search_link_1" text,
  "search_link_2" text,
  "search_link_3" text
);

CREATE INDEX ON "chat_history" ("id");

CREATE INDEX ON "search_history" ("id");

CREATE INDEX ON "search_history" ("chat_id");

CREATE INDEX ON "llm_processing_steps" ("id");

CREATE INDEX ON "links" ("id");

CREATE INDEX ON "links_searches" ("id");

ALTER TABLE "search_history" ADD FOREIGN KEY ("chat_id") REFERENCES "chat_history" ("id");

ALTER TABLE "llm_processing_steps" ADD FOREIGN KEY ("chat_id") REFERENCES "chat_history" ("id");

